 !****************************************************************  
 ! OutputError.f90
 ! 
 ! Created on: Aug 4, 2014
 ! Author: ninoy
 !***************************************************************** 

 SUBROUTINE OutputError(time)
#include <finclude/petscdef.h>
    use petscksp
    use MD_Parameter
    use MD_Quantity
    use MD_Helper
    implicit none

    PetscScalar phii(1)
    PetscOffset offset
    PetscErrorCode ierr
    integer, intent(in) :: time
    integer :: i,j,k,row,ierror
!    real(kind=double), dimension(0:2) :: xcord
    character(len=200) :: format
    format = "(A10, I3)"

    print *, ''
    print *, '**********************'
    print *, 'writing vtk for error'
    print *, '**********************'
    print *, ''
    print format, 'time=',time

    call VecGetArray(phi,phii,offset,ierr)

    open(unit=0, file='data/Error.vtk',status='UNKNOWN',action= 'WRITE',&
        position='rewind',iostat= ierror)

100 FORMAT(F8.4,F8.4,F8.4)

    write(0,'(a)')"# vtk DataFile Version 2.0"
    write(0,'(a)')' Generated by Ninoy Rahman'
    write(0,'(a)')'ASCII'
    write(0,*)''
    write(0,'(a)')'DATASET UNSTRUCTURED_GRID'
    write(0,*)'POINTS ', inc*jnc*knc ,' double'

    do k = kmin, kmax
        do j = jmin, jmax
            do i = imin, imax
!                call GetCordinate(i,j,k,xcord)
                write(0,100) x(i),y(j),z(k)
            end do
        end do
    end do

    write(0,*) ''
    write(0,*) 'POINT_DATA ', inc*jnc*knc
    write(0,'(a)') 'SCALARS Error double 1'
    write(0,'(a)') 'LOOKUP_TABLE DEFAULT'

    do k = kmin, kmax
        do j = jmin, jmax
            do i = imin, imax
                write(0,*) error(i,j,k)
            end do
        end do
    end do

    call VecRestoreArray(phi,phii,offset,ierr)

    close(unit=0)

END SUBROUTINE OutputError
