 !****************************************************************  
 ! Output_3D.f90
 ! 
 ! Created on: Jul 23, 2014
 ! Author: ninoy
 !***************************************************************** 

SUBROUTINE Output_3D(time)
#include <finclude/petscdef.h>
    use petscksp
    use MD_Parameter
    use MD_Quantity
    use MD_PETScQuantity
    use MD_Helper
    implicit none

    PetscScalar, pointer :: phii(:)
    PetscErrorCode ierr
    integer, intent(in) :: time
    integer :: i,j,k,row,ierror
    character(len=200) :: format
    character(len=100) :: rankstr
    character(len=100) :: timestr

    if(rank .eq. master) then
        format = "(A10, I3)"
        print *, ''
        print *, '*****************'
        print *, 'writing 3D output'
        print *, '*****************'
        print *, ''
        print format, 'time=',time
    endif

    format = '(I5.5)'
    write (rankstr, format) rank
    write (timestr, format) time

    open(unit=0, file='data/Potential.'//trim(timestr)//'.'//trim(rankstr)//'.vtk', &
        status='UNKNOWN',action= 'WRITE', position='rewind',iostat= ierror)

100 FORMAT(F8.4,F8.4,F8.4)

    write(0,'(a)')"# vtk DataFile Version 2.0"
    write(0,'(a)')' Generated by Ninoy Rahman'
    write(0,'(a)')'ASCII'
    write(0,*)''
    write(0,'(a)')'DATASET UNSTRUCTURED_GRID'
    write(0,*)'POINTS ', ilnc*jlnc*klnc ,' double'

    do k = kmin, kmax
        do j = jmin, jmax
            do i = imin, imax
                write(0,100) x(i),y(j),z(k)
            end do
        end do
    end do

    write(0,*) ''
    write(0,*) 'POINT_DATA ', ilnc*jlnc*klnc
    write(0,'(a)') 'SCALARS Density double 1'
    write(0,'(a)') 'LOOKUP_TABLE DEFAULT'

    do k = kmin, kmax
        do j = jmin, jmax
            do i = imin, imax
                write(0,*) rho(i,j,k)
            end do
        end do
    end do

    write(0,*) ''
    write(0,'(a)') 'SCALARS Potential double 1'
    write(0,'(a)') 'LOOKUP_TABLE DEFAULT'

    call VecGetArrayF90(phi,phii,ierr)

    do k = kmin, kmax
        do j = jmin, jmax
            do i = imin, imax
                row = GetLocalIndex(i,j,k)
                write(0,*) PetscRealPart(phii(row+1))
            end do
        end do
    end do

    call VecRestoreArrayF90(phi,phii,ierr)

    close(unit=0)

END SUBROUTINE Output_3D
